[package]
name = "genos-camera"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "genos-camera"
path = "src/main.rs"

[dependencies]
genos-input = { path = "../../crates/input" }
genos-scene = { path = "../../crates/scene" }
genos-window = { path = "../../crates/window" }
genos-render = { path = "../../crates/render" }
